### ISSUE TITLE
🐞 maximized window moved from large screen to small one, it cannot adjust automatically

### ISSUE THREAD

**Issue by HugoChoi-AI** [MrKai77/Loop#678]
### Bug Description

The maximized application window should automatically adjust according to the screen size. 
Currently, moving from a small screen to a large screen works fine, 
but moving from a large screen to a small screen doesn't.

### Steps To Reproduce

0: now i working in multiple screen in same workspace mode.
1: I open a APP windows in maximized size on a big screen 
2: then i move the cursor to the small screen and press the shortcut key combination of fn + space.

### Expected Behavior

It should adjust the window size to fit the screen's maximized size

### Actual Behavior

The APP windows have now moved to the small screen, but their size is larger than that of the screen, causing some content to be beyond the screen.
(Refer to the picture 2 The content on the left side of the window has gone beyond the screen.
It should be automatically adjusted to look like picture 3)

### Screenshots

![Image](https://github.com/user-attachments/assets/12757f59-756e-4ec8-a744-868b6d44beaa)

![Image](https://github.com/user-attachments/assets/e13ac4da-0e66-4237-b914-d144fe410bb0)

![Image](https://github.com/user-attachments/assets/ba19a093-937b-4120-805e-94e1f9cbaec7)

### macOS Version

Sequoia 15.2 (24C101)

### Loop Version

Version 1.2.0 (1410)

### Final Checks

- [x] My issue is written in English
- [x] My issue title is descriptive
- [x] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Thank you, will take a look!

**Comment by MrKai77** [comment]
@HugoChoi-AI  can you reproduce this issue on the latest release? This should be fixed now.

**Comment by HugoChoi-AI** [comment]
Yes, I checked it out, and most apps are working properly now. However, some apps still have a slight issue where the left side goes beyond the border. Anyway, it’s not a big deal—you can go ahead and close this ticket.  

<img width="936" height="273" alt="Image" src="https://github.com/user-attachments/assets/68dfd953-1706-45c7-82a7-ee811d02e627" />
