### ISSUE TITLE
✨ Custom keybindings

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#75]
### Feature Request Description

Although I found the current mapping pretty good, it would be nice to give the users the option to choose their custom keybindings.

This also helps with [Trigger Key conflicts](https://github.com/MrKai77/Loop/issues/74).

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
I've been wanting to implement this for a while now too! The only problem is that I am having trouble figuring out how to configuration UI would look like. However, since Loop's UI to show the user the current keybinds isn't that good to begin with, I guess this is a good opportunity to improve it!

**Comment by Zabriskije** [comment]
I think you did a good job with Loop's UI. The current Keybindings section it's spot-on for its purpose.
To give you an idea of how to implement it, here's an example from Moom's menu:

![example](https://github.com/MrKai77/Loop/assets/101254295/ba8e8906-e2f3-405d-9e17-55574aeaa789)

I don't know how complicated is the cells/tiles selection and all the other bells and whistles, but it looks hard. A simpler solution could be to just have a drop-down menu for action selection, a blank input field for keybindings, and a +/- button for adding/removing them.

**Comment by MrKai77** [comment]
This does look pretty cool! I'll see what I can do!

**Comment by Zabriskije** [comment]
Not sure if this needs a new issue since you're going to redo the Keybindings section, but in `beta.11` I can't use <kbd>Shift</kbd> as a trigger key. Works fine on `beta.10`.

**Comment by MrKai77** [comment]
Yup, this changed in #40, where you can press <kbd>Trigger Key</kbd> + <kbd>Shift</kbd> + <kbd>Space</kbd> to toggle fullscreen mode on a window. However, it could make sense to set this back to <kbd>Trigger Key</kbd> +  <kbd>F</kbd>, so that <kbd>shift</kbd> is useable as trigger key again (and this would also simplify the new keybind system a lot :P). 

*But*, <kbd>Trigger Key</kbd> + <kbd>Shift</kbd> + <kbd>Space</kbd> also makes sense as a keybind to toggle fullscreen because <kbd>Trigger Key</kbd> + <kbd>Space</kbd> is already a keybind to maximize a window. 

Another option we could consider is being able to double-click a key (if it's a single key) as well. For example, a single click on <kbd>Space</kbd> would be maximize, but a double click could be toggle fullscreen.

What are your thoughts on this? 

EDIT: It looks like I have forgotten to update the README to reflect the latest changes about the <kbd>Shift</kbd> key. Sorry about that! I can see why this would cause a some confusion.

**Comment by Zabriskije** [comment]
I was checking some features to see if they were working as intended, so if they didn't, I could have given you more work 😂
So yes, I just asked that because I was testing keys found in the README.

Double-click would be awesome though. I'd go for that.

**Comment by MrKai77** [comment]
Haha, I just changed my mind! With #82 and the current implementation of using <kbd>Trigger Key</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd> to toggle fullscreen, I think that it would be better to keep the <kbd>Shift</kbd> key as a modifier key. I also found that being able to double-click a key would conflict with when the user is cycling through directions (with the WASD/arrow keys), so that makes it a less of a feasible option. 

Anyways, here's what I have so far (aka a VERY early prototype) (it's a scrollable view):
<img width="602" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/207e2c60-e60a-4fba-adf7-62c4988546bd">

As you can see, the keys are still only displayed as keycodes, so I will need to find a way to convert those into human-readable keys :)

The only concern I have about this is that many of the resize options have duplicates, because there are two keycaps for some of the options (example: both the <kbd>Right Arrow</kbd> key and  <kbd>D</kbd> key can cycle through directions on the right-side). What do you think of this? (I'm also going to change the "dropdown" into a picker menu for less complexity)

Also another question: I think it would make more sense to have one dedicated tab for customizing keybinds, much like Moom. Would it be user-intuitive to move the trigger key settings into the "General tab"?

**Comment by Zabriskije** [comment]
> Haha, I just changed my mind! With #82 and the current implementation of using Trigger Key + Shift + F to toggle fullscreen, I think that it would be better to keep the Shift key as a modifier key.

If you make the users pick their keys with an input field, there's no need to exclude <kbd>Shift</kbd> as a trigger key.

Examples:
- Trigger Key: <kbd>Control</kbd> + <kbd>Option</kbd>, Fullscreen: <kbd>Shift</kbd> + <kbd>F</kbd>
- Trigger Key: <kbd>Control</kbd> + <kbd>Shift</kbd>, Fullscreen: <kbd>Option</kbd> + <kbd>F</kbd>
- Trigger Key: <kbd>Control</kbd> + <kbd>Option</kbd> + <kbd>Shift</kbd>, Fullscreen:  <kbd>F</kbd>

All do the same thing, but it's up to the users to decide what's best for them.

Other apps like Rectangle and Magnet have their default key combinations but allow users to customize them later (image below Rectangle).

![Rectangle](https://user-images.githubusercontent.com/13651296/183785536-a67a2e2a-7c55-4c19-9bf8-482e734b1632.png)

So you can have – for example – the default trigger key set to <kbd>Left Control</kbd> and the fullscreen toggle to <kbd>Shift</kbd> + <kbd>F</kbd> without limiting users' customizability.

> The only concern I have about this is that many of the resize options have duplicates, because there are two keycaps for some of the options (example: both the Right Arrow key and D key can cycle through directions on the right-side). What do you think of this? (I'm also going to change the "dropdown" into a picker menu for less complexity)

If the resize options are going to be added or removed by the user, I see no problem with that. If they will be fixed, that's ok too, make another resize option in the same section called `Secondary key` or `Alternative key`.

> Also another question: I think it would make more sense to have one dedicated tab for customizing keybinds, much like Moom. Would it be user-intuitive to move the trigger key settings into the "General tab"?

I would move the `Trigger Key` section to `Radial Menu` since that's what the trigger key triggers, and leave the `Keybindings` where they are now.

**Comment by MrKai77** [comment]
Sorry for the late update! But I think I have finished! Here's the end result!
<img width="602" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/47aae6ec-5656-4a72-bd37-f41c7eb32890">
And here's a screenshot for keybinds with two keys:
<img width="602" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/6210f1dc-03aa-4094-adff-85b27fe6c1db">
These are the default set of keybindings. I tried to thin-down the preset keybinds, so that the user is free to add their own, but also have a few for quick-access upon installation.

As you can see, I did end up keeping the radial menu's trigger key settings in the keybinding section, since I thought it still made much more sense for it to stay there. 

As for the shift key, the user can set it as an additional key for a keybind *only* when the shift key is not set as the trigger key.

Overall, I'm pretty happy with the end result!

Feel free to try out this latest build, and I would be grateful for your help in identifying any bugs :)
[Loop.zip](https://github.com/MrKai77/Loop/files/13445839/Loop.zip)

**Comment by Zabriskije** [comment]
When using multiple keys, arrows work fine but other keys don’t get recorded unless another modifier key is pressed:

![Multiple keys bug](https://github.com/MrKai77/Loop/assets/101254295/68e047db-74a7-443e-8a89-230993bf90dc)

It would be nice to also have the option to set multiple keys as Trigger Key, as well as to use them in Keybinds.

What's the difference between `Cycle` and `Halves`?

**Comment by MrKai77** [comment]
Thank you so much!

> What's the difference between Cycle and Halves?

Cycle allows you to press the same key *while* the radial menu has been triggered to repeatedly cycle through halves, thirds, and two thirds. I'll try and make this more obvious in the UI!

**Comment by MrKai77** [comment]
Alright, I tried implementing everything in your previous comment! Being able to use multiple keys as the trigger key also half-fixes #74, so that also makes things easier!

Anyways, here's the latest test build:
[Loop.zip](https://github.com/MrKai77/Loop/files/13455120/Loop.zip)
Again, please let me know if you encounter any bugs!

**Comment by Zabriskije** [comment]
That's way better!

1. Loop doesn't work on itself (e.g. I can't center the Loop window using Loop)
2. Only <kbd>Shift</kbd> can be added to Keybinds, other modification keys do not work. When added, the symbol `⇧` doesn't appear inside it's box
3. It's possible to edit multiple keybinds simultaneously
4. Longer key combinations disappear under the window right margin (this is a bit picky so I don't think that's a problem, just pointing it out)

**Comment by MrKai77** [comment]
> 1. Loop doesn't work on itself

Yep, this is something currently done on purpose as otherwise, Loop sometimes (uncontrollably) crashes itself 😅. This might be something worth making another feature request for :)

> 2. Only <kbd>Shift</kbd> can be added to Keybinds, other modification keys do not work.

Fixed!

>  3. It's possible to edit multiple keybinds simultaneously

Also fixed!

> 4. Longer key combinations disappear under the window right margin

Great job finding this bug! I added a 5-key limit to all keybinds so this shouldn't happen anymore!

Thank you so much for always extensively testing these test builds! Here's the latest one:
~[Loop.zip](https://github.com/MrKai77/Loop/files/13462325/Loop.zip)~ [EDIT: found a bug, fixing that now]

**Comment by MrKai77** [comment]
Fixed that bug! Here's the latest build:
[Loop.zip](https://github.com/MrKai77/Loop/files/13462410/Loop.zip)

**Comment by Zabriskije** [comment]
> > 1. Loop doesn't work on itself
> 
> Yep, this is something currently done on purpose as otherwise, Loop sometimes (uncontrollably) crashes itself 😅. This might be something worth making another feature request for :)

Will do!

> > 4. Longer key combinations disappear under the window right margin
> 
> Great job finding this bug! I added a 5-key limit to all keybinds so this shouldn't happen anymore!

If you set the Trigger Key to more than 1 key it still happens. Is there a way to calculate the total number of keys used in both the Trigger Key and the Keybinds and set that number to 6? This way you're safe even with the longest keybind name (Horizontal Center Third).

I've also found that after setting multiple times the Keybinds or the Trigger Key, sometimes the input field is still active and keeps recording inputs. Unfortunately, I don't know how to exactly reproduce this (in the GIF below, KeyCastr doesn't display when one or multiple modifier keys are pressed without any other normal key, so when you see the Trigger Key bouncing that's what I'm doing)

![Input field still active bug](https://github.com/MrKai77/Loop/assets/101254295/8c36f09b-2477-4b61-8443-aa11fffabc2a)

This was also present in previous builds, including the latest release.

> Thank you so much for always extensively testing these test builds!

More than happy to help :)

**Comment by MrKai77** [comment]
> If you set the Trigger Key to more than 1 key it still happens. Is there a way to calculate the total number of keys used in both the Trigger Key and the Keybinds and set that number to 6?

Done! I also added a 5 key limit to the trigger key as well so that the same graphical bug doesn't happen at the trigger key selector as well!

> I've also found that after setting multiple times the Keybinds or the Trigger Key, sometimes the input field is still active and keeps recording inputs.

Interesting! I tried brute-forcing this bug by setting a keybind over and over, and I was able to reproduce this bug. I couldn't come up with a recipe to reproduce this either, but I looked at a few other codebases to see how they avoided the problem, and tried implementing that into Loop as well. I can't reproduce the bug anymore so hopefully that fixed it! (or at least made it happen much less often!)

Here's the latest build:
[Loop.zip](https://github.com/MrKai77/Loop/files/13465939/Loop.zip)

**Comment by Zabriskije** [comment]
> > If you set the Trigger Key to more than 1 key it still happens. Is there a way to calculate the total number of keys used in both the Trigger Key and the Keybinds and set that number to 6?
> 
> Done! I also added a 5 key limit to the trigger key as well so that the same graphical bug doesn't happen at the trigger key selector as well!

If you set a 5 keys combination for a keybind and then set a 2 or more keys combination for the Trigger Key this still happens, but I guess it's acceptable.

> > I've also found that after setting multiple times the Keybinds or the Trigger Key, sometimes the input field is still active and keeps recording inputs.
> 
> Interesting! I tried brute-forcing this bug by setting a keybind over and over, and I was able to reproduce this bug. I couldn't come up with a recipe to reproduce this either, but I looked at a few other codebases to see how they avoided the problem, and tried implementing that into Loop as well. I can't reproduce the bug anymore so hopefully that fixed it! (or at least made it happen much less often!)

This happened again, but I think I've found how to reproduce this: if you click two times on an input field without pressing any keys after the first click, it seems like the first click is still listening for inputs (works with both Trigger Key and Keybinds).

New: when pressing `Restore Defaults` the Trigger Key shown is still the old one. Reopening Loop's window fix it.

**Comment by MrKai77** [comment]
> If you click two times on an input field without pressing any keys after the first click, it seems like the first click is still listening for inputs (works with both Trigger Key and Keybinds).

I can't believe that this was what was producing the bug! This made fixing it so much easier! Thank you so much!

> When pressing `Restore Defaults` the Trigger Key shown is still the old one. Reopening Loop's window fix it.

Fixed!

Here's the latest build!
[Loop.zip](https://github.com/MrKai77/Loop/files/13469210/Loop.zip)

**Comment by Zabriskije** [comment]
All the previous bugs seems fixed 🚀

I've found that if I set a custom Trigger Key with two or more keys, sometimes Loops doesn't work:

![Multiple Trigger Keys](https://github.com/MrKai77/Loop/assets/101254295/3c5e6db0-2805-4a21-845e-13a8e503d64b)

**Comment by MrKai77** [comment]
Awesome! Thank you so much for your help!

> if I set a custom Trigger Key with two or more keys, sometimes Loops doesn't work

Fixed! I also managed to improve the efficiency of how this is processed!

Here's the latest build:
[Loop.zip](https://github.com/MrKai77/Loop/files/13482233/Loop.zip)

If this all seems good, I'll open a PR and merge this into the `develop` branch!

**Comment by Zabriskije** [comment]
I've tested it out for a few hours and everything seems working, good job!
