### ISSUE TITLE
🐞 Modifier Key Conflicts After “Cycle Backward with Shift” Feature

### ISSUE THREAD

**Issue by AlejandroVolkova** [MrKai77/Loop#803]
### Bug Description

Loop appears to be significantly disrupted by the recent addition of the “Cycle backward with Shift” feature, even when this feature is disabled.

In my setup, the main trigger key is Left Fn, but Loop is also responding to Cmd and Shift, causing unexpected behavior across macOS native apps. This leads to interference with standard keyboard shortcuts.

Main Issues:

•  Finder Selection Freeze: Holding Shift + Arrow should continuously select files. With Loop active, selection freezes, and sometimes the window moves instead.

•  Navigation Hijack: Pressing Cmd + Arrow Up/Down (used to enter folders or go back) triggers Loop’s window manager instead of executing the native action.

I recommend a temporary regression to the previous stable state, prior to the addition of “Cycle backward with Shift”, until the feature can be properly scoped and implemented without interfering with native shortcuts.

### Steps To Reproduce

1. Disable the “Cycle backward with Shift” feature.

2. Open Finder and attempt to select multiple files using Shift + Arrow Down.
  ⁠◦   Expected: Continuous file selection.
  ⁠◦  Actual: Selection freezes. If Shift is the last key pressed, the window moves in that direction.

3. In Finder Press Cmd + Arrow Up/Down to navigate folders.
  ⁠◦   Expected: Enter folder or go back.
  ⁠◦   Actual: Loop triggers window movement. If Cmd is the last key pressed, it behaves like a trigger.

6.  this can be reproduced with TextEdit as well, type some text, press any arrow key, then press Cmd or Shift.
  ⁠◦  Expected: Text selection or cursor movement.
  ⁠◦  Actual: Window moves in the arrow direction.

### Expected Behavior

-

### Actual Behavior

-

### macOS Version

macOS Sequoia 15.6.1

### Loop Version

Version 1.4.0 (1535)

### Final Checks

- [x] My issue is written in English
- [x] My issue title is descriptive
- [x] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by MrKai77** [comment]
Hey @AlejandroVolkova, thanks for reporting. I can't reproduce this bug on my side, so I'm guessing that this bug only affects certain types of setups. 

However, I have also reworked the method Loop uses to trigger in this PR: https://github.com/MrKai77/Loop/pull/802, and it should hopefully fix this bug too. Once it's merged, would you be able to test a development build to ensure that it's been correctly fixed on your side too? I will update you when the time comes if you are able to :)

**Comment by AlejandroVolkova** [comment]
Thanks for following up @MrKai77 ! I’ll do some additional digging to see if anything in my setup might be contributing to the issue. That said, I haven’t experienced this problem with the current stable release, which I had to roll back to, since the last few developer builds were unusable for me due to the issues I described earlier.

Once PR #802 is merged, I’m happy to test the development build and verify whether the fix works on my end. I’ll keep an eye out and run proper tests when you reach out. If I uncover any new details in the meantime, I’ll be sure to share them, though to be honest, I doubt it, given that everything works fine in the public release :)

**Comment by MrKai77** [comment]
@AlejandroVolkova would you be able to test the latest development version now? Should be fixed!

**Comment by AlejandroVolkova** [comment]
Hey @MrKai77 ! Just confirmed the bug is fixed in the latest pre-release build 1.538. everything’s running smoothly now.

Also, side note: the updated animations? Subtle but seriously impressive. Nice work on that front :)

**Comment by injust** [comment]
I think I'm still seeing this issue on: Version 🧪 1.4.0 (1546).

I also use left fn as my trigger key. After I updated from latest stable to latest dev, shift-left/right arrow started snapping my windows.
